import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { Josefin_Sans } from "next/font/google";

const theFont = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Partial<Metadata> = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      className={
        theFont.className + " bg-gray-200 transition-3 text-sm lg:text-base"
      }
      data-theme="maga"
      lang="en"
    >
      <body className="overflow-x-hidden">{children}</body>
    </html>
  );
}
